---
:ems:
  :ems_scvmm:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:http_proxy:
  :scvmm:
    :host:
    :password:
    :port:
    :user:
:workers:
  :worker_base:
    :queue_worker_base:
      :ems_metrics_collector_worker:
        :ems_metrics_collector_worker_microsoft: {}
